# Notebook

## Project: The dynamics of diversity and abundance of symbionts in the metatranscriptome

In [1]:
import pandas as pd
import os
from collections import Counter
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import numpy as np
np.set_printoptions(suppress=True)
from glob import glob

### Sample description:

In [2]:
df = pd.read_csv('/Users/lolitiy/Documents/inst_bioinf_19_20/project/metadata_all.csv', sep=';', header=None, names=['Name', 'Conditions'], decimal=',')
pd.set_option('display.max_rows', 62)
pd.set_option('display.max_columns', None)
pd.set_option('max_colwidth', 800)
pd.set_option('display.expand_frame_repr', False)

In [3]:
df

           Name                                           Conditions
0       EveB3_1                             control 3 hours sample 1
1       EveB3_2                             control 3 hours sample 2
2       EveB3_3                             control 3 hours sample 3
3       EveB3_4                             control 3 hours sample 4
4      EveB24_1                            control 24 hours sample 1
5      EveB24_2                            control 24 hours sample 2
6      EveB24_3                            control 24 hours sample 3
7      EveCd3_1                        LC10 cadmium 3 hours sample 1
8      EveCd3_2                        LC10 cadmium 3 hours sample 2
9      EveCd3_3                        LC10 cadmium 3 hours sample 3
10     EveCd3_4                        LC10 cadmium 3 hours sample 4
11    EveCd24_1                       LC10 cadmium 24 hours sample 1
12    EveCd24_2                       LC10 cadmium 24 hours sample 2
13    EveCd24_3                       LC10 cadmium 24 hours sample 3
14    EveCd24_4                       LC10 cadmium 24 hours sample 4
15   Eve10LT3_1                                LT10 3 hours sample 1
16   Eve10LT3_2                                LT10 3 hours sample 2
17   Eve10LT3_3                                LT10 3 hours sample 3
18   Eve10LT3_4                                LT10 3 hours sample 4
19  Eve10LT24_1                               LT10 24 hours sample 1
20  Eve10LT24_2                               LT10 24 hours sample 2
21  Eve10LT24_3                               LT10 24 hours sample 3
22  Eve10LT24_4                               LT10 24 hours sample 4
23     EvePB3_1                        0.1% acetone 3 hours sample 1
24     EvePB3_2                        0.1% acetone 3 hours sample 2
25    EvePB24_1                       0.1% acetone 24 hours sample 1
26    EvePB24_2                       0.1% acetone 24 hours sample 2
27    EvePB24_3                       0.1% acetone 24 hours sample 3
28      EveP3_1                 1 mg/L phenanthrene 3 hours sample 1
29      EveP3_2                 1 mg/L phenanthrene 3 hours sample 2
30      EveP3_3                 1 mg/L phenanthrene 3 hours sample 3
31      EveP3_4                 1 mg/L phenanthrene 3 hours sample 4
32     EveP24_1                1 mg/L phenanthrene 24 hours sample 1
33     EveP24_2                1 mg/L phenanthrene 24 hours sample 2
34     EveP24_3                1 mg/L phenanthrene 24 hours sample 3
35     EveP24_4                1 mg/L phenanthrene 24 hours sample 4
36      EveB6_1                    initial control for EveT sample 1
37      EveB6_2                    initial control for EveT sample 2
38      EveB6_3                    initial control for EveT sample 3
39      EveB6_4                    initial control for EveT sample 4
40     EveB12_1                 parallel control for EveT12 sample 1
41     EveB12_2                 parallel control for EveT12 sample 2
42     EveB12_3                 parallel control for EveT12 sample 3
43     EveB12_4                 parallel control for EveT12 sample 4
44     EveB18_1                 parallel control for EveT18 sample 1
45     EveB18_2                 parallel control for EveT18 sample 2
46     EveB18_3                 parallel control for EveT18 sample 3
47     EveB18_4                 parallel control for EveT18 sample 4
48   EveB24_1_6                 parallel control for EveT24 sample 1
49   EveB24_3_7                 parallel control for EveT24 sample 3
50     EveB24_4                 parallel control for EveT24 sample 4
51     EveT12_1   gradual temperature increase 12 degrees C sample 1
52     EveT12_2   gradual temperature increase 12 degrees C sample 2
53     EveT12_3   gradual temperature increase 12 degrees C sample 3
54     EveT18_1   gradual temperature increase 18 degrees C sample 1
55     EveT18_2   gradual temperature increase 18 degrees C sample 2
56     EveT18_3   gradual temperature increase 18 degrees C sample 3
57     EveT18_4   gradual temperature increase 18 degrees C sample 4
58     EveT24_1   gradual temperature increase 24 degrees C sample 1
59     EveT24_2   gradual temperature increase 24 degrees C sample 2
60     EveT24_3   gradual temperature increase 24 degrees C sample 3
61     EveT24_4   gradual temperature increase 24 degrees C sample 4

## Run ribotagger

### Ribotagger - v4 region 16/18s rRNA

In [ ]:
!ribotagger.pl -r v4 -i sample_name_F.fastq.gz sample_name_R.fastq.gz -o sample_name.v4

In [ ]:
!batch.pl -r v4 -i sample_name.v4 -o sample_name

###  .v4 Tables with 16/18s rRNA

In [167]:
#Path
path = '/Users/lolitiy/Documents/inst_bioinf_19_20/project/test'

#Names for all tables
sample_names = os.listdir(path)
sample_names = [x for x in sample_names if x.endswith('.v4') and not x.startswith('~')]

#List with all tables 
#Keep only the columns with the OTE (long1) and its count (long.total.count)
sample_files = glob('/Users/lolitiy/Documents/inst_bioinf_19_20/project/test/*v4')
list_of_dfs = [pd.read_csv(sample_file, skiprows=6, sep='\t', usecols=lambda c: c in {'long.total.count', 'long1'}, header=0).dropna() for sample_file in sample_files]
list_of_dfs

[     long.total.count                                              long1
 0                 164  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 1                 487  TGGGCGTAAAGAGTGCACAGGTGGTTATATAAGTTTGGTGTTAAAT...
 2                  82  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 3                  38  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 4                 182  TGCAGTTAAAAAGCTCGTAGTTGAATCTCTGGTCTAGGACGATCGT...
 ..                ...                                                ...
 492                 1  TGGGCGTAAAGAGTGCACAGGTGGTTATATAAGTTTGGTGTTAAAT...
 499                 1  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 500                 1  TGGGTTTAAAGGGTGCGTAGGCGGACCTGTAAGTCAGTGGTGAAAT...
 501                 1  TGCAGTTAAAACGCTCGTAGTTTGAAATATTTAATTGGCAGCGTGG...
 503                 1  TGGGCGTAAAGCGTGTGTAGGCGGCCAAGTAAGTTGGATGTGAAAG...

 [294 rows x 2 columns],
      long.total.count                                              long1
 0                 252  TGGGCGTAAAGAGTGCACAGGTGGTTATATAAGTTTGGTGTTAAAT...
 2                  38  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 3                 100  TGGGCGTAAAGCGCGCGTAGGTGGTTCGTTAAGTTGGATGTGAAAT...
 4                 100  TGGGCGTAAAGGGTACGTAGGTGGTCTTTTAAGTCGGATGTGAAAT...
 6                  92  TGCAGTTAAAAAGTTCGTAGTTGAATTTCTGAGCGCAGCGGCGGTC...
 ..                ...                                                ...
 282                 2  TGGGCGTAAAGGGTGTGTAGGCGGCGAGGCAAGTCCGATGTGAAAG...
 284                 2  TGGGTTTAAAGGGTGCGTAGGCGGTTAATTAAGTCAGTCGTTAAAG...
 286                 2  TGGGTTTAAAGGGTCCGTAGGCGGTCTTGTAAGTCAGTGGTGAAAG...
 287                 2  TGGGCGTAAAGCGCGTGTAGGCTGCCTCGCAAGTCGGATGTGAAAG...
 288                 2  TGCAGTTGAAAAGCTCGTAGTCGTATTTCTGATGGGTTGACGCTGG...

 [225 rows x 2 columns],
      long.total.count                                              long1
 0                 161  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 1                 556  TGGGCGTAAAGCGCGCGTAGGCGGTTTTTTAAGTCTGATGTGAAAG...
 2                 228  TGGGCGTAAAGCGCGCGTAGGCGGTTTCTTAAGTCTGATGTGAAAG...
 3                 110  TGGGCGTAAAGAGTGCACAGGTGGTTATATAAGTTTGGTGTTAAAT...
 4                  28  TGCAGTTAAAAAGCTCGTAGTTGAAAATCTGATTGTTCAGGTCATC...
 ..                ...                                                ...
 627                 1  TGCAGTTAAAACGCTCGTAGTTTGAATTATTTCGGCACTTGGCGGC...
 628                 1  TAGGCGTAAAGGGTGCGTAGGTGGCTTAAAACTTTATTTTTCAAAT...
 629                 1  TGGGTTTAAAGGGTGCGTAGGCTGTTGTGTAAGTCTGTTGTGAAAG...
 630                 1  TGGGCGTAAAGCGCGCGTAGGCGGTTTTTTAAGCCAGAGGTGAAAG...
 631                 1  TGGGCGTAAAGCGCGTGTAGGCGGTTTTGTAAGTTGGATGTGAAAT...

 [412 rows x 2 columns],
      long.total.count                                              long1
 0                 198  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 1                 107  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 2                 438  TGCAGTTAAAAAGCTCGTAGTTGAATCTCTGGTCTAGGACGATCGT...
 3                  62  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 4                 344  TGGGCGTAAAGAGTGCACAGGTGGTTATATAAGTTTGGTGTTAAAT...
 ..                ...                                                ...
 639                 1  TGGGCGTAAAGCGCGCGCAGGTGGCCACGTAAGTCGGGTGTGAAAG...
 641                 1  TGGGCGTAAAGAGTGCACAGGTGGCTATATAAGTTTGGTGTTAAAT...
 645                 1  TGGGTTTAAAGGGTGCGTAGGCGGTCTGATAAGTCAGTCGTGAAAT...
 647                 1  TGGGTTTAAAGGGTGCGTAGGCTGTTTTATAAGTCAGCGGTGAAAG...
 648                 1  TGGGTTTAAAGGGTGCGTAGGCGGTTTAATAAGTCAGTCGTTAAAG...

 [365 rows x 2 columns],
       long.total.count                                              long1
 0                 5912  TGGGCGTAAAGGGTGCGTAGGTTGTTTTTCAAGTTGGGTGTGAAAG...
 1                  131  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 2                  506  TGCAGTTAAAAAGCTCGTAGTTGAATCTCTGGTCTAGGACGATCGT...
 3                  118  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 4                   81  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 ...                ...                                                ...
 1158                 1  TGGGCGTAAAGGGTGCGTAGGTTGTTTTTCCAGTTGGGTGTGAAAG...
 1159                 1  TGGGCGTAAAGCGCACGTAGGCGGATCAGAAAGTCAGAGGTGAAAT...
 1165                 1  TGGGTTTAAAGGGTGCGTAGGCGGGTAGATAAGTCAGAGGTGAAAG...
 1179                 1  TGCAGTTAAAAAGCTCGTAGTTGAATATCCGGCGTTTCTGACGTCT...
 1180                 1  TGGGCGTAAAGCGTCTGCAGGTGGTTTAAAAAGTCTAGTGTCAAAG...

 [479 rows x 2 columns],
      long.total.count                                              long1
 0                 162  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 1                  58  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 2                  92  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 3                  38  TGCAGTTAAAAAGCTCGTAGTTGAATATCCGGCGTCTTTGACGTCT...
 4                  81  TGCAGTTAAAAAGCTCGTAGTTGAATATCCGGCGTCATTGACGTCT...
 ..                ...                                                ...
 450                 1  TGGGCGTAAAGCGTGCGCAGGCGGTTATATAAGACAGTTGTGAAAT...
 451                 1  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 452                 1  TGGGTTTAAAGGGTCCGTAGGCGGTTTGATAAGTCAGTGGTGAAAG...
 454                 1  TGGGTTTAAAGGGTGCGTAGGCGGCTTTTTAAGTCGATAGCTAAAT...
 457                 1  TGGGCGTAAAGGGTGCGTAGGCGGCGCGGAAAGTCAGGGGTGAAAT...

 [333 rows x 2 columns],
      long.total.count                                              long1
 0                 257  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 1                  86  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 2                 103  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 3                 231  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGCTGATCCTGTC...
 4                  43  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTTCGGGTCCCC...
 ..                ...                                                ...
 700                 1  TGGGCGTAAAGGGCGCGTAGGCGGAAAGATAAGTCAGATGTGAAAT...
 701                 1  TGGGTGTAAAGGATACGTAGGCTGTTTAAAATAAACTAAATCTGTA...
 706                 1  TGGGCGTAAAGCGTGCGCAGGCGGTCTTGCAAGACAGGTGTGAAAT...
 708                 1  TGGGCGTAAAGAGCTCGTAGGCGGGGGCGTGCGTCCGAAAAGAAAT...
 710                 1  TGGGCGTAAAGAGCTCGTAGGCGGCTTTGTAAGTCGGATGTGAAAG...

 [428 rows x 2 columns],
      long.total.count                                              long1
 0                   8  TGCGGTTAAAAAGCTCGTAGTTGGGAGAAGGAGACATTGAGAAAAA...
 1                  22  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 3                 138  TGGGCGTAAAGCGCGCGTAGGTGGTTCGTTAAGTTGGATGTGAAAT...
 4                 126  TGGGCGTAAAGAGTGCACAGGTGGTTATATAAGTTTGGTGTTAAAT...
 5                 100  TGGGTTTAAAGGGTGCGTAGGCGGTTTATTAAGTCAGTGGTGAAAG...
 ..                ...                                                ...
 337                 2  TGGGCGTAAAGAGCTCGTAGGCGGGAGCGTAAGTCTGAAAGGAAAT...
 339                 2  TGGGTTTAAAGGGTGCGTAGGTGGGTCTGTAAGTCAGCGGTGAAAT...
 340                 2  TGGGCGTAAAAAGTTTTTAGATGGTTATTAAAAAATAACTTGAGTT...
 341                 2  TGGGCGTAAAGGGTGCGTAGGCGGTCTCGTAAGTCAGATGTGAAAT...
 342                 2  TGGGTTTAAAGGGTGCGTAGGCGGACTTGTAAGTCAGTGGTGAAAT...

 [242 rows x 2 columns],
      long.total.count                                              long1
 0                 130  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 1                  48  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 2                  33  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 3                  23  TGCAGTTAAAAAGCTCGTAGTTGAATATCCGGCGTCTTTGACGTCT...
 4                   9  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTTCGGGTCTCA...
 ..                ...                                                ...
 484                 1  TGGGCTTAAAGAGTTCGTAGGCGGTCTTGTAGGTGAGGTGTGAAAG...
 485                 1  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGTTGTATTGGGCCTA...
 486                 1  TGGGCGTAAAGCGCGCGTAGGTGGTTTGTTAAGTTGAATGTGAAAT...
 487                 1  TGGGCGTAAAGCGTGCGTAGGTGGTTTGTTAAGTCTGATGTGAAAG...
 488                 1  TGGGCTTAAAGCGTGCGTAGGCGGCTCTGAAAGTTAGGTGTGAAAT...

 [305 rows x 2 columns],
      long.total.count                                              long1
 0                  53  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 1                  43  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 2                  22  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 3                 154  TGGGCGTAAAGAGTGCACAGGTGGTTATATAAGTTTGGTGTTAAAT...
 4                  19  TGCAGTTAAAAAGCTCGTAGTTGAATATCCGGCGTCTTTGACGTCT...
 ..                ...                                                ...
 440                 1  TGGGCGTAAAGCATATGTAGGTTGTTCTAAAAGCCGAAGGTTTAAT...
 441                 1  TGGGTTTAAAGGGTGCGTAGGCGGTTTATTAAGTCAGAGGTGAAAG...
 450                 1  TGGGCGTAAAGCGTGTGTAGGCTGTTTAGAAAGTCTTTCATGAAAT...
 451                 1  TGGGCGTAAAGGGTGCGTAGGCGGCGCGGAAAGTCAGGGGTGAAAT...
 453                 1  TGGGCGTAAAGCGCGTGTAGGCGGTTTTGTAAGTTGGATGTGAAAT...

 [292 rows x 2 columns],
      long.total.count                                              long1
 0                 295  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 1                  91  TGCAGTTAAAAAGCTCGTAGTTGAATTTCTGGCTGGTTGTCTCAAC...
 2                 140  TGCAGTTAAAAAGCTCGTAGTTGAATCTCTGGTCTAGGACGATCGT...
 3                 179  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGCTGATCCTGTC...
 4                  61  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTTTGGGTTCCT...
 ..                ...                                                ...
 608                 1  TGGGCGTAAAGCGCATGTAGGCGGCCTAGCAGGTCGGATGTGAAAG...
 610                 1  TGGGCGTAAAGGGTGTGTAGGCGGTATTTTAAGTCGATTGTGTAAT...
 611                 1  TGCAGTTAAAAAGCTCGTAGCTGAAACTTGGTTTAGAATTGCAGGG...
 613                 1  TGCAGTTAAAAAGCTCGTAGTTGGATTTTGAAGCTATTTATTATGG...
 615                 1  TGGGTGTAAAGGGTACGTAGGTTGCTTAGTAAGTGGTGAGTGAAAC...

 [367 rows x 2 columns],
      long.total.count                                              long1
 0                 294  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 1                  69  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 2                 104  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 3                  38  TGCAGTTAAAAAGCTCGTAGTTGAATATCCGGCGTCTTTGACGTCT...
 4                 164  TGCAGTTAAAAAGCTCGTAGTTGAATATCCGGCGTCATTGACGTCT...
 ..                ...                                                ...
 492                 1  TGGGCGTAAAGCGTACGTAGGCGGCTTTTTAAGTCAGAGGTGAAAT...
 493                 1  TGGGTTTAAAGGGTGCGTAGGCGGCTTGATAAGTCGGTGGTTAAAG...
 494                 1  TGGGTTTAAAGGGTGCGTAGGCGGGATTTTAAGTCAGTGGTGAAAG...
 495                 1  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTAGGCCTC...
 498                 1  TGGGCGTAAAGGGTGCGTAGGCTGTCTTTTTAAGTCAATTGTGAAA...

 [387 rows x 2 columns],
      long.total.count                                              long1
 0                   3  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 1                   6  TGCGGTTAAAAAGCTCGTAGTTGGGAGAAGGAGACATTGAGAAAAA...
 2                  29  TGCAGTTAAAAAGCTCGTAGTTGAAGCTATGATATGTCCTTTGAAA...
 3                   4  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 4                  13  TGGGTTTAAAGGGTGCGTAGGCGGCTTTATAAGTCTGTGGTTAAAG...
 ..                ...                                                ...
 225                 1  TGGGTTTAAAGGGTCCGTAGGCGGGCTAATAAGTCAGTGGTGAAAT...
 230                 1  TGGGCGTAAAGCGTGCGTAGGCGGTTTGATAAGTCGATTGTGAAAG...
 231                 1  TGGGTTTAAAGGGTCCGTAGGCGGTTTAATAAGTCAGTGGTGAAAT...
 232                 1  TGTATTTAAAAAGCTCGTAGTTGAAGCGTGGGTGTCTAATCAAATG...
 234                 1  TGCTGTTAAAGGGTTCGTAGTTGAACTGTGGAGCATGATTCAGAGA...

 [139 rows x 2 columns],
      long.total.count                                              long1
 0                 270  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 1                 509  TGGGCGTAAAGAGTGCACAGGTGGTTATATAAGTTTGGTGTTAAAT...
 2                  57  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 3                 265  TGCAGTTAAAAAGCTCGTAGTTGAATCTCTGGTCTAGGACGATCGT...
 4                  95  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTTCGGGTCCCC...
 ..                ...                                                ...
 639                 1  TGGGTGTAAAGGGTCCGTAGGTGGATTTTTAAGTCAGGTATAAAAG...
 640                 1  TGGGCGTAAAGCGTGCGCAGGCGGTCCTGCAAGACAGGTGTGAAAT...
 641                 1  TGCAGTTAAAAAGCTCGTAGTTGGATTTCAAGGTGTAGACGGGGTA...
 642                 1  TGGGTTTAAAGGGTGCGTAGGCGGTTTATTAAGTCAGTAGTGAAAG...
 645                 1  TGGGCGTAAAGGGTGCGTAGGCGGATGATTAAGTCGGAGGTGAAAG...

 [362 rows x 2 columns],
      long.total.count                                              long1
 0                 592  TGGGCGTAAAGAGTGCACAGGTGGTTATATAAGTTTGGTGTTAAAT...
 1                  46  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 2                 424  TGGGCGTAAAGGGTGCGTAGGTTGTTTTTCAAGTTGGGTGTGAAAG...
 3                 202  TGCAGTTAAAAAGTTCGTAGTTGAATTTCTGAGCGCAGCGGCGGTC...
 4                   4  TGCAGTTAAAAAGCTCGTAGTTGGACTTGGGAGGTTCTTAAATACG...
 ..                ...                                                ...
 295                 2  TGGGCGTAAAGCGTATGTAGGCGGTTGTATAAGTCTTTTATTAAAG...
 296                 2  TGGGTGTAAAGTGTGCGTAGGCTGTTATGTAAGTTAATTGTGAAAT...
 301                 2  TGGGCGTAAAGCGCACGTAGGCGGATTGTTAAGTGAGGGGTGAAAT...
 302                 2  TGGGTGTAAAGGATACGTAGGCTATTTAAAATAAACTAAATCTGGA...
 303                 2  AGGGTTTAAAGGGTCCGTAGGCGGTTTAATAAGTCAGTGGTGAAAT...

 [202 rows x 2 columns],
      long.total.count                                              long1
 0                 304  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 1                 281  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 2                  71  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 3                 305  TGGGCGTAAAGAGTGCACAGGTGGTTATATAAGTTTGGTGTTAAAT...
 4                  96  TGCAGTTAAAAAGCTCGTAGTTGAATATCCGGCGTCTTTGACGTCT...
 ..                ...                                                ...
 531                 1  TGGGTTTAAAGGGTGCGTAGGCGGACTATTAAGTCAAATGTGAAAG...
 532                 1  TGGGTGTAAAGGGTGCGTAGATGGCTTAATAAGTTACATGTAAAAA...
 533                 1  TGGGCGTAAAGCGCACGTAGGCGGATTGGAAAGTTGGAGATGAAAT...
 535                 1  TGGGCGTAAAGCGTGCGCAGGCGGTCTTGCAAGACAGATGTGAAAT...
 538                 1  TGGGCGTAAAGAGTATGTAGGCGGTTTATTAAGTCTGATGTGAAAG...

 [369 rows x 2 columns],
      long.total.count                                              long1
 0                 475  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 1                 415  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 2                  96  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 3                 703  TGGGCGTAAAGGGTGCGTAGGTTGTTTTTCAAGTTGGGTGTGAAAG...
 4                  85  TGCAGTTAAAAAGCTCGTAGTTGAATATCCGGCGTCTTTGACGTCT...
 ..                ...                                                ...
 786                 1  TGGGCGTAAAGCGCGTGTAGGCGGCTAGGTCAGTCAGATGTGAAAG...
 788                 1  TGGGCGTAAAGGGTGCGTAGGTTGTTTTTAAAGTTGGGTGTGAAAG...
 800                 1  TGGGCGTAAAGCGCGCGTAGGCGGTTATGTAAGTTGGATGTGAAAT...
 804                 1  TGGGTTTAAAGGGTCCGTAGGCGGTCTTATAAGTCAGTGGTGAAAG...
 806                 1  TGGGCGTAAAGCGTGCGCAGGCGGTTATGTAAGTCAGATGTGAAAT...

 [431 rows x 2 columns],
      long.total.count                                              long1
 0                 229  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 1                 129  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 2                 119  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 3                 238  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGCTGATCCTGTC...
 4                  70  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTTCGGGTCCCC...
 ..                ...                                                ...
 694                 1  TGCAGTTAAAAAGCTCGTAGTTGAATCTCTGGTCTAGGACGATCGT...
 696                 1  TGGGCGTAAAGGGTGCGTAGGTGGTCCCTTAAGTCAATTGCGAAAT...
 701                 1  TGCAGTTAAAAAGCTCGTAGTTGAAATCCTGGCTGCTGATCCTGTC...
 704                 1  TGCAGTTAAAACGCTCGTAGTTTGAATTATTTCGGTGTCAGGCTGG...
 710                 1  TGGGCGTAAAGAGTGCGTAGGCGGTTTAGTAAGTTGGAAGTGAAAG...

 [430 rows x 2 columns],
      long.total.count                                              long1
 0                  62  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 1                  34  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 2                  20  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 3                  72  TGCAGTTAAAAAGCTCGTAGTTGAATCTCTGGTCTAGGACGATCGT...
 4                  15  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTTCGGGTCCCC...
 ..                ...                                                ...
 314                 1  TGGGCATAAAGGGATCATAGGAGCTCAGCTGCTTATTGCAGGGATC...
 315                 1  TGGGCGTAAAGCGCGTGTAGGCGGCTAGGTCAGTCAGATGTGAAAG...
 317                 1  TGGGCGTAAAGCGCACGTAGGCGGACCGGAAAGTCAGAAGTGAAAT...
 323                 1  TGGGTTTAAAGGGAGCGTAGGTGGGTTGGTAAGTCAGCGGTGAAAT...
 330                 1  TGGGCGTAAAGAGTGCGTAGGCGGTTGTTTAAGTCGAATGTGAAAG...

 [181 rows x 2 columns],
      long.total.count                                              long1
 0                  48  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 1                  96  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGCTGATCCTGTC...
 2                  72  TGGGCGTAAAGCGTGCGCAGGCGGTCTTGCAAGACAGGTGTGAAAT...
 3                  80  TGGGCGTAAAGCGCACGTAGGCGGATTGTTTAGTTAGAGGTGAAAT...
 4                  74  TGGGTTTAAAGGGTGCGTAGGCGGGACATTAAGTCAGTGGTGAAAG...
 ..                ...                                                ...
 219                 2  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGCTGATCCTCTC...
 221                 2  TGGGCGTAAAGGGTTCATAGGTATCTTAAGTGATAATTTTTTGCTA...
 222                 2  TGGGCGTAAAGGGTGCGTAGGTGGTCCCTTAAGTCAATTGCGAAAT...
 223                 2  TGGGCGTAAAGGGCGTGTAGGCGGGATGTTAAGTCTGGTTTTAAAG...
 224                 2  TGGGTGTAAAGAGTTGCGCAGGCGGTCCTGTTAGCAAGTAGTGAAA...

 [176 rows x 2 columns],
      long.total.count                                              long1
 0                 403  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 1                 369  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 2                  16  TGCAGTTAAAAAGCTCGTAGTTGGACTTGGGAGGTTCTTAAATACG...
 3                 523  TGGGCGTAAAGAGTGCACAGGTGGTTATATAAGTTTGGTGTTAAAT...
 4                 300  TGCAGTTAAAAAGCTCGTAGTTGAATATCCGGCGTCATTGACGTCT...
 ..                ...                                                ...
 538                 1  AGGGTTTAAAGGGTCCGTAGGCGGGCCAGTAAGTCAGTGGTGAAAT...
 539                 1  TGGGCGTAAAGGGTGCGTAGGCGGCGCGGAAAGTCAGGGGTGAAAT...
 541                 1  TGGGCGTAAAGCGTGCGCAGGCGACTGTGAAAGTTGATGGTGAAAT...
 546                 1  TGCTGTTAAAAGGCTTTTAGTGCACCCTCACGGACGTCTGCTAGAG...
 548                 1  TGGGCGTAAAGGGTGCGTAGGCGGATGATTAAGTCGGAGGTGAAAG...

 [383 rows x 2 columns],
      long.total.count                                              long1
 0                  79  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTGGTTGCTGGGTTCGTC...
 1                  16  TGCGGTTAAAAAGCTCGTAGTTGGGAGAAGGAGACATTGAGAAAAA...
 2                  48  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTATTGGGCCTA...
 3                  34  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGGCTGTATTGGGCCTC...
 4                   9  TGCAGTTAAAAAGCTCGTAGTTGAAATTCTGATTGTTCGGGTCCCC...
 ..                ...                                                ...
 457                 1  TGCTGTTAAAGGGTTCGTAGTTGAATTGTGGCTCACCGAGCCCTGC...
 460                 1  TGCAGTTAAAAAGCTCGTAGTTGAAACTCTAGTTGCTGGGTTCGTC...
 464                 1  TGGGCGTAAAGGGCGCGTAGGTGGTTTGGTAAGTTGGATGTGAAAT...

In [164]:
#Export function of csv tables
func  = lambda x, y: x.to_csv(y, index=False)

#Export tables containing 16/18s rRNA sequences
list(map(func, list_of_dfs, sample_names))

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [165]:
#Change extension v4 to tab
!cd 
for f in *.v4; do
    mv -- "$f" "$(basename -- "$f" .v4).tab"
done

IndentationError: unexpected indent (<ipython-input-165-fe3d69d75f1f>, line 3)

### Creating .fasta files from retrieved tables

In [ ]:
#!/usr/local/bin/python

docstring= """
DESCRIPTION
    Convert tabular to FASTA

USAGE:
    python tab2fasta.py <tab-file> <sequence column> <header column 1> <header column 2> <header column n>  > <outfile>
"""

import sys
if len(sys.argv) < 4:
    sys.exit('\nThree or more arguments required%s' %(docstring))
    
infile= open(sys.argv[1])
seqix= int(sys.argv[2]) - 1 
headerix= sys.argv[3:]
headerix= [(int(x) - 1) for x in headerix]
count = 0

for line in infile:
    line= line.strip().split(',')
    header= '>' + '_'.join(count + [line[i] for i in headerix])
    count = count + 1
    print(header)
    print(line[seqix])

infile.close()

In [153]:
!for f in *.tab; do 
python3 /Users/lolitiy/Documents/inst_bioinf_19_20/python/python_homework/tabtofasta.py "$f" 2 1 > ""$f".fasta"; 
done

/bin/sh: -c: line 0: syntax error near unexpected token `dopython3'
/bin/sh: -c: line 0: `for f in *.v4; dopython3 tab2fasta.py '

## IDTAXA Classification

### or use http://www2.decipher.codes/Classification.html

In [ ]:

%R
# load the DECIPHER library in R
if (!requireNamespace("BiocManager", quietly=TRUE))
  install.packages("BiocManager")
BiocManager::install("DECIPHER")

library(DECIPHER)

# specify the path to the FASTA file (in quotes)
fas <- "/Users/lolitiy/Documents/inst_bioinf_19_20/project/Samples/EveB3_1/EveB3_1_v4.fasta"
seqs <- readDNAStringSet(fas) # or readRNAStringSet
# remove any gaps (if needed)
seqs <- RemoveGaps(seqs)

# for help, see the IdTaxa help page (optional)
?IdTaxa

# load a training set object (trainingSet)
# see http://DECIPHER.codes/Downloads.html
load("/Users/lolitiy/Desktop/SILVA_SSU_r132_March2018.RData")

# classify the sequences
ids <- IdTaxa(seqs,
              SILVA_SSU_r132_March2018,
              strand="both", # or "top" if same as trainingSet
              threshold=60, # 60 (very high) or 50 (high)
              processors=NULL) # use all available processors
# look at the results
(print(ids))
assignment <- sapply(ids, 
                     function(id) {
                       paste (id$taxon, 
                              "(",
                              round(id$confidence, digits = 1),
                              "%)",
                              sep = "",
                              collapse = "; ")
                     })
write.csv(assignment, "/Users/lolitiy/Desktop/1.csv")

phylum <- sapply(ids,
                 function(x) {
                   w <- which(x$rank=="phylum")
                   if (length(w) != 1) {
                     "unknown"
                   } else {
                     x$taxon[w]
                   } })
table(phylum)

taxon <- sapply(ids,
                function(x)
                  x$taxon[length(x$taxon)])
samples <- gsub(".*; (.+?)_.*", "\\1", names(seqs))
taxaTbl <- table(taxon, samples)
taxaTbl <- t(t(taxaTbl)/colSums(taxaTbl))
include <- which(rowMeans(taxaTbl) >= 0.04)

## Make a classification table

In [19]:
# Path
path = '/Users/lolitiy/Documents/inst_bioinf_19_20/project/samles/'

In [20]:
# names of all .xlsx classification files

sample_names = os.listdir(path)
sample_names = [x for x in sample_names if x.endswith('.xlsx') and not x.startswith('~')]

In [21]:
sample_names

['EveB3_2.xlsx',
 'EveB12_4.xlsx',
 'EveB6_1.xlsx',
 'EveCd3_3.xlsx',
 'EveB24_4.xlsx',
 'EveB18_2.xlsx',
 'EveP24_2.xlsx',
 'EveCd24_2.xlsx',
 'EveB24_1_6.xlsx',
 'Eve10LT24_3.xlsx',
 'EveB24_3_7.xlsx',
 'Eve10LT3_1.xlsx',
 'Eve10LT24_2.xlsx',
 'EveCd24_3.xlsx',
 'EvePB3_1.xlsx',
 'EveP24_3.xlsx',
 'EveB18_3.xlsx',
 'EveT24_1.xlsx',
 'EveCd3_2.xlsx',
 'EveT12_1.xlsx',
 'EveB3_3.xlsx',
 'EveP24_4.xlsx',
 'EveCd24_4.xlsx',
 'EveB3_4.xlsx',
 'EveB12_2.xlsx',
 'EvePB24_2.xlsx',
 'EveB24_2.xlsx',
 'EveB18_4.xlsx',
 'EveT18_1.xlsx',
 'EveB24_3.xlsx',
 'EvePB24_3.xlsx',
 'EveCd3_4.xlsx',
 'EveP3_1.xlsx',
 'EveB12_3.xlsx',
 'Eve10LT24_4.xlsx',
 'Eve10LT3_4.xlsx',
 'EveT18_2.xlsx',
 'EveT24_4.xlsx',
 'EveP3_2.xlsx',
 'EveB24h_1.xlsx',
 'EveB12_1.xlsx',
 'EveB6_4.xlsx',
 'EveP3_3.xlsx',
 'EvePB24_1.xlsx',
 'EveT18_3.xlsx',
 'EveB24_2_6.xlsx',
 'EveT18_4.xlsx',
 'EveT24_2.xlsx',
 'EveCd3_1.xlsx',
 'EveP3_4.xlsx',
 'EveB6_3.xlsx',
 'EveT12_2.xlsx',
 'Eve10LT3_2.xlsx',
 'Eve10LT24_1.xlsx',
 'EvePB3_2.xlsx',
 'EveP24_1.xlsx',
 'EveCd24_1.xlsx',
 'Eve10LT3_3.xlsx',
 'EveB3_1.xlsx',
 'EveT12_3.xlsx',
 'EveB6_2.xlsx',
 'EveT24_3.xlsx',
 'EveB18_1.xlsx']

In [22]:
samples = {}

for name in sample_names:
    
    nice_name = name[:-5]
    
    # only column with taxonomic classes
    df = pd.read_excel(os.path.join(path, name), usecols= lambda c: c in {'count', 'H'}, header = 0).dropna()
    result = []
    # count OTE
    for count, H in df.itertuples(index=False):
        result.extend([H] * count)
    samples[nice_name] = Counter(result)
samples

{'EveB3_2': Counter({'Gammaproteobacteria': 670,
          'Alphaproteobacteria': 284,
          'Holozoa': 52,
          'Bacteroidia': 152,
          'Alveolata': 42,
          'Bacilli': 16,
          'Armatimonadia': 6,
          'unclassified_Proteobacteria': 22,
          'Actinobacteria': 6,
          'Verrucomicrobiae': 8,
          'Deltaproteobacteria': 12,
          'unclassified_Bacteroidetes': 2,
          'Acidimicrobiia': 2,
          'Oxyphotobacteria': 2,
          'Clostridia': 2}),
 'EveB12_4': Counter({'Alveolata': 111,
          'Holozoa': 38,
          'unclassified_SAR': 14,
          'Gammaproteobacteria': 149,
          'Sericytochromatia': 15,
          'Bacteroidia': 24,
          'Alphaproteobacteria': 22,
          'Bacilli': 8,
          'Discoba': 1,
          'Stramenopiles': 1,
          'unclassified_Proteobacteria': 1,
          'Actinobacteria': 2}),
 'EveB6_1': Counter({'Alveolata': 63,
          'Holozoa': 83,
          'Gammaproteobacteria': 206,
          'Alphaproteobacteria': 68,
          'Bacteroidia': 49,
          'unclassified_Bacteroidetes': 4,
          'Sericytochromatia': 2,
          'unclassified_Proteobacteria': 5,
          'Armatimonadia': 2,
          'Actinobacteria': 2,
          'Verrucomicrobiae': 2,
          'Oxyphotobacteria': 1,
          'Deltaproteobacteria': 3,
          'Blastocatellia (Subgroup 4)': 1,
          'Deinococci': 1,
          'Discoba': 1}),
 'EveCd3_3': Counter({'Holozoa': 410,
          'Alphaproteobacteria': 276,
          'Gammaproteobacteria': 624,
          'Bacteroidia': 158,
          'Alveolata': 26,
          'Armatimonadia': 10,
          'Clostridia': 8,
          'Deltaproteobacteria': 16,
          'unclassified_Bacteroidetes': 4,
          'Oxyphotobacteria': 8,
          'Nucletmycea': 2,
          'Bacilli': 2,
          'Actinobacteria': 2,
          'unclassified_Proteobacteria': 2,
          'Verrucomicrobiae': 4,
          'Stramenopiles': 2,
          'Sericytochromatia': 2,
          'Blastocatellia (Subgroup 4)': 2}),
 'EveB24_4': Counter({'Bacilli': 615,
          'Gammaproteobacteria': 333,
          'Alveolata': 51,
          'Holozoa': 53,
          'Actinobacteria': 21,
          'Bacteroidia': 40,
          'unclassified_Proteobacteria': 10,
          'Alphaproteobacteria': 47,
          'Deltaproteobacteria': 14,
          'Rhizaria': 6,
          'Armatimonadia': 3,
          'Blastocatellia (Subgroup 4)': 2,
          'unclassified_Bacteroidetes': 2,
          'unclassified_SAR': 1,
          'Discoba': 2,
          'Acidobacteriia': 4,
          'unclassified_Firmicutes': 2,
          'Nucletmycea': 1,
          'Verrucomicrobiae': 1,
          'Chloroplastida': 1}),
 'EveB18_2': Counter({'Alveolata': 262,
          'Holozoa': 229,
          'Gammaproteobacteria': 607,
          'Alphaproteobacteria': 166,
          'Bacteroidia': 132,
          'Rhizaria': 7,
          'unclassified_SAR': 5,
          'Nucletmycea': 1,
          'Stramenopiles': 13,
          'Oxyphotobacteria': 10,
          'Deltaproteobacteria': 27,
          'Blastocatellia (Subgroup 4)': 11,
          'Discoba': 6,
          'Armatimonadia': 3,
          'Chloroplastida': 2,
          'Sericytochromatia': 5,
          'unclassified_Proteobacteria': 5,
          'Discosea': 3,
          'Deinococci': 2,
          'Bacilli': 3,
          'Verrucomicrobiae': 8,
          'Planctomycetacia': 4,
          'Anaerolineae': 2,
          'Acidobacteriia': 2,
          'Leptospirae': 1}),
 'EveP24_2': Counter({'Alveolata': 594,
          'Holozoa': 149,
          'Alphaproteobacteria': 165,
          'unclassified_Proteobacteria': 42,
          'Bacteroidia': 187,
          'Gammaproteobacteria': 337,
          'Verrucomicrobiae': 6,
          'Oxyphotobacteria': 4,
          'Actinobacteria': 9,
          'Bacilli': 6,
          'Armatimonadia': 2,
          'Deltaproteobacteria': 3,
          'Sericytochromatia': 3,
          'Stramenopiles': 2,
          'Rhizaria': 1,
          'Clostridia': 1,
          'Blastocatellia (Subgroup 4)': 1,
          'Discoba': 1,
          'Acidobacteriia': 1}),
 'EveCd24_2': Counter({'Alphaproteobacteria': 294,
          'Gammaproteobacteria': 584,
          'Bacteroidia': 182,
          'unclassified_Bacteroidetes': 38,
          'Holozoa': 32,
          'Alveolata': 20,
          'Blastocatellia (Subgroup 4)': 8,
          'unclassified_Proteobacteria': 8,
          'Armatimonadia': 8,
          'Deltaproteobacteria': 12,
          'Sericytochromatia': 6,
          'Oxyphotobacteria': 2,
          'Stramenopiles': 2,
          'Bacilli': 6,
          'Verrucomicrobiae': 4,
          'Actinobacteria': 2}),
 'EveB24_1_6': Counter({'Gammaproteobacteria': 332,
          'Alveolata': 78,
          'Holozoa': 101,
          'unclassified_SAR': 25,
          'Bacteroidia': 48,
          'unclassified_Proteobacteria': 19,
          'Nucletmycea': 4,
          'Alphaproteobacteria': 54,
          'Chloroplastida': 7,
          'Oxyphotobacteria': 4,
          'Discoba': 5,
          'Actinobacteria': 1,
          'Deltaproteobacteria': 6,
          'Armatimonadia': 1,
          'Deinococci': 2,
          'Rhizaria': 2,
          'Ancyromonadida': 1,
          'Blastocatellia (Subgroup 4)': 1,
          'Bacilli': 1,
          'Nitrospira': 1,
          'Verrucomicrobiae': 1,
          'Sericytochromatia': 1}),
 'Eve10LT24_3': Counter({'Holozoa': 29,
          'Alveolata': 6,
          'Bacteroidia': 59,
          'Gammaproteobacteria': 158,
          'Alphaproteobacteria': 93,
          'Chloroplastida': 7,
          'Discosea': 3,
          'Tubulinea': 2,
          'Blastocatellia (Subgroup 4)': 3,
          'Verrucomicrobiae': 3,
          'Armatimonadia': 2,
          'Deltaproteobacteria': 3,
          'Sericytochromatia': 2,
          'Actinobacteria': 2,
          'unclassified_Actinobacteria': 1,
          'Mycamoeba': 1,
          'Bacilli': 1,
          'Discoba': 1}),
 'EveB24_3_7': Counter({'Holozoa': 91,
          'Alveolata': 25,
          'Gammaproteobacteria': 141,
          'Actinobacteria': 33,
          'Bacteroidia': 38,
          'Tubulinea': 2,
          'unclassified_SAR': 4,
          'unclassified_Bacteroidetes': 2,
          'unclassified_Firmicutes': 3,
          'Rhizaria': 6,
          'Deltaproteobacteria': 9,
          'Alphaproteobacteria': 22,
          'Nucletmycea': 1,
          'Negativicutes': 2,
          'Bacilli': 6,
          'Acidobacteriia': 1,
          'Clostridia': 1,
          'Discoba': 1}),
 'Eve10LT3_1': Counter({'SAR': 568,
          'unclassified_Eukaryota': 156,
          'Opisthokonta': 128,
          'Proteobacteria': 1168,
          'unclassified_Bacteria': 192,
          'Bacteroidetes': 243,
          'Archaeplastida': 5,
          'Acidobacteria': 4,
          'Verrucomicrobia': 7,
          'Cyanobacteria': 7,
          'Armatimonadetes': 2,
          'Deinococcus-Thermus': 2,
          'Chloroflexi': 1,
          'Excavata': 1,
          'Planctomycetes': 1}),
 'Eve10LT24_2': Counter({'Gammaproteobacteria': 1068,
          'Bacteroidia': 302,
          'Alphaproteobacteria': 508,
          'Stramenopiles': 60,
          'Holozoa': 12,
          'Alveolata': 10,
          'Deltaproteobacteria': 22,
          'Sericytochromatia': 6,
          'Bacilli': 26,
          'Blastocatellia (Subgroup 4)': 8,
          'unclassified_Proteobacteria': 6,
          'Actinobacteria': 10,
          'Oxyphotobacteria': 8,
          'unclassified_SAR': 4,
          'Armatimonadia': 2,
          'Chloroplastida': 2,
          'Clostridia': 2}),
 'EveCd24_3': Counter({'Holozoa': 822,
          'Gammaproteobacteria': 638,
          'Alveolata': 34,
          'unclassified_Proteobacteria': 88,
          'Bacteroidia': 192,
          'Alphaproteobacteria': 240,
          'unclassified_Bacteroidetes': 28,
          'Armatimonadia': 10,
          'Verrucomicrobiae': 16,
          'Actinobacteria': 12,
          'Blastocatellia (Subgroup 4)': 6,
          'Deltaproteobacteria': 4,
          'Oxyphotobacteria': 4,
          'Sericytochromatia': 2,
          'Stramenopiles': 2,
          'Campylobacteria': 2,
          'Discoba': 2}),
 'EvePB3_1': Counter({'Alveolata': 497,
          'Gammaproteobacteria': 392,
          'Holozoa': 56,
          'Alphaproteobacteria': 167,
          'Bacteroidia': 112,
          'unclassified_Proteobacteria': 44,
          'Deltaproteobacteria': 5,
          'Sericytochromatia': 3,
          'Verrucomicrobiae': 4,
          'Tubulinea': 1,
          'Armatimonadia': 3,
          'Oxyphotobacteria': 3,
          'unclassified_Planctomycetes': 2,
          'Acidobacteriia': 1,
          'unclassified_SAR': 1,
          'Actinobacteria': 1,
          'Stramenopiles': 1,
          'Deinococci': 1}),
 'EveP24_3': Counter({'Alveolata': 1328,
          'Holozoa': 172,
          'Bacteroidia': 366,
          'Gammaproteobacteria': 559,
          'Alphaproteobacteria': 245,
          'unclassified_SAR': 33,
          'Verrucomicrobiae': 22,
          'Blastocatellia (Subgroup 4)': 4,
          'Deinococci': 5,
          'Rhizaria': 5,
          'Bacilli': 4,
          'Deltaproteobacteria': 11,
          'Planctomycetacia': 6,
          'unclassified_Proteobacteria': 7,
          'Armatimonadia': 2,
          'Acidobacteriia': 2,
          'Actinobacteria': 2,
          'Oxyphotobacteria': 3,
          'unclassified_Bacteroidetes': 4,
          'Campylobacteria': 2,
          'Mollicutes': 1,
          'Stramenopiles': 2,
          'Clostridia': 1,
          'Nucletmycea': 1,
          'Acidimicrobiia': 1,
          'Sericytochromatia': 1}),
 'EveB18_3': Counter({'Alveolata': 282,
          'Gammaproteobacteria': 450,
          'Holozoa': 82,
          'unclassified_SAR': 24,
          'Bacteroidia': 108,
          'Alphaproteobacteria': 95,
          'Deltaproteobacteria': 32,
          'Discoba': 9,
          'Rhizaria': 6,
          'unclassified_Proteobacteria': 18,
          'Armatimonadia': 8,
          'Blastocatellia (Subgroup 4)': 9,
          'Bacilli': 5,
          'Sericytochromatia': 5,
          'Nucletmycea': 3,
          'Acidobacteriia': 4,
          'Negativicutes': 3,
          'Actinobacteria': 3,
          'Deinococci': 1,
          'Oxyphotobacteria': 1,
          'Planctomycetacia': 1,
          'Verrucomicrobiae': 2,
          'Stramenopiles': 2,
          'Clostridia': 2}),
 'EveT24_1': Counter({'Gammaproteobacteria': 476,
          'Deltaproteobacteria': 168,
          'Alveolata': 41,
          'Discoba': 38,
          'Bacteroidia': 212,
          'Verrucomicrobiae': 49,
          'Alphaproteobacteria': 162,
          'Armatimonadia': 29,
          'Goniomonas': 3,
          'Ancyromonadida': 4,
          'unclassified_SAR': 9,
          'Blastocatellia (Subgroup 4)': 9,
          'unclassified_Proteobacteria': 14,
          'Chloroplastida': 2,
          'Acidobacteriia': 7,
          'unclassified_Bacteroidetes': 3,
          'Holozoa': 13,
          'Oxyphotobacteria': 3,
          'Discosea': 7,
          'Actinobacteria': 4,
          'Stramenopiles': 2,
          'Bacilli': 2,
          'Sericytochromatia': 3,
          'Fusobacteriia': 1,
          'Deinococci': 1,
          'Planctomycetacia': 2,
          'Anaerolineae': 1}),
 'EveCd3_2': Counter({'Holozoa': 238,
          'Gammaproteobacteria': 730,
          'Alveolata': 90,
          'Alphaproteobacteria': 224,
          'Bacteroidia': 120,
          'Blastocatellia (Subgroup 4)': 8,
          'Deltaproteobacteria': 10,
          'Actinobacteria': 8,
          'Stramenopiles': 6,
          'Armatimonadia': 2,
          'Bacilli': 6,
          'Sericytochromatia': 4,
          'unclassified_Proteobacteria': 4,
          'Verrucomicrobiae': 2,
          'Oxyphotobacteria': 2,
          'unclassified_Bacteroidetes': 2,
          'unclassified_SAR': 2,
          'Planctomycetacia': 2}),
 'EveT12_1': Counter({'Alveolata': 374,
          'Gammaproteobacteria': 392,
          'Bacteroidia': 246,
          'Holozoa': 56,
          'Alphaproteobacteria': 162,
          'unclassified_SAR': 6,
          'Deltaproteobacteria': 10,
          'Chloroplastida': 6,
          'Actinobacteria': 2,
          'unclassified_Proteobacteria': 12,
          'Blastocatellia (Subgroup 4)': 5,
          'Oxyphotobacteria': 2,
          'Verrucomicrobiae': 4,
          'Armatimonadia': 2,
          'Sericytochromatia': 2,
          'Deinococci': 2,
          'Stramenopiles': 1}),
 'EveB3_3': Counter({'class': 990, 'kingdom': 72, 'superkingdom': 58}),
 'EveP24_4': Counter({'Alveolata': 710,
          'Holozoa': 158,
          'Gammaproteobacteria': 346,
          'Alphaproteobacteria': 118,
          'Bacteroidia': 146,
          'Verrucomicrobiae': 16,
          'unclassified_Bacteroidetes': 6,
          'Oxyphotobacteria': 4,
          'Actinobacteria': 5,
          'Deltaproteobacteria': 5,
          'Bacilli': 4,
          'Discosea': 2,
          'Armatimonadia': 3,
          'Stramenopiles': 1,
          'Clostridia': 4,
          'Planctomycetacia': 2,
          'Deinococci': 1,
          'Acidobacteriia': 3,
          'unclassified_Proteobacteria': 1,
          'Negativicutes': 1,
          'unclassified_Actinobacteria': 1}),
 'EveCd24_4': Counter({'Holozoa': 559,
          'Alveolata': 281,
          'Bacteroidia': 217,
          'Gammaproteobacteria': 276,
          'unclassified_SAR': 6,
          'Alphaproteobacteria': 98,
          'Verrucomicrobiae': 20,
          'unclassified_Proteobacteria': 10,
          'Armatimonadia': 9,
          'Oxyphotobacteria': 9,
          'Blastocatellia (Subgroup 4)': 2,
          'Deltaproteobacteria': 12,
          'Acidobacteriia': 2,
          'Bacilli': 3,
          'Deinococci': 3,
          'Mollicutes': 2,
          'Stramenopiles': 2,
          'Discoba': 2,
          'Sericytochromatia': 2,
          'Planctomycetacia': 1}),
 'EveB3_4': Counter({'unclassified_Proteobacteria': 202,
          'Alveolata': 22,
          'Holozoa': 56,
          'Alphaproteobacteria': 166,
          'Gammaproteobacteria': 354,
          'Bacteroidia': 110,
          'unclassified_SAR': 16,
          'Verrucomicrobiae': 20,
          'Oxyphotobacteria': 6,
          'Deltaproteobacteria': 6,
          'Stramenopiles': 4,
          'Actinobacteria': 6,
          'Bacilli': 2,
          'Acidobacteriia': 4,
          'Blastocatellia (Subgroup 4)': 2,
          'Deinococci': 2}),
 'EveB12_2': Counter({'Alveolata': 197,
          'Holozoa': 293,
          'Gammaproteobacteria': 197,
          'unclassified_SAR': 28,
          'Bacteroidia': 60,
          'Chloroplastida': 1,
          'Stramenopiles': 10,
          'Nucletmycea': 4,
          'Alphaproteobacteria': 18,
          'Sericytochromatia': 2,
          'Oxyphotobacteria': 3,
          'Armatimonadia': 2,
          'Negativicutes': 1,
          'Chlamydiae': 1,
          'Actinobacteria': 2,
          'unclassified_Proteobacteria': 1,
          'unclassified_Bacteroidetes': 1,
          'Deltaproteobacteria': 1,
          'Bacilli': 1}),
 'EvePB24_2': Counter({'Alveolata': 951,
          'Gammaproteobacteria': 600,
          'Holozoa': 91,
          'Bacteroidia': 190,
          'unclassified_Proteobacteria': 43,
          'Alphaproteobacteria': 237,
          'unclassified_Bacteroidetes': 21,
          'Deltaproteobacteria': 8,
          'Armatimonadia': 4,
          'Verrucomicrobiae': 11,
          'Sericytochromatia': 2,
          'Blastocatellia (Subgroup 4)': 3,
          'Oxyphotobacteria': 3,
          'Bacilli': 3,
          'Leptospirae': 2,
          'Deinococci': 2,
          'Clostridia': 1,
          'unclassified_SAR': 1,
          'Discoba': 2,
          'Actinobacteria': 1,
          'Stramenopiles': 1}),
 'EveB24_2': Counter({'Gammaproteobacteria': 544,
          'Alphaproteobacteria': 260,
          'Bacteroidia': 174,
          'Alveolata': 42,
          'Holozoa': 4,
          'unclassified_Bacteroidetes': 16,
          'unclassified_Proteobacteria': 14,
          'Bacilli': 8,
          'Sericytochromatia': 6,
          'Oxyphotobacteria': 4,
          'Actinobacteria': 18,
          'Stramenopiles': 6,
          'Armatimonadia': 4,
          'Verrucomicrobiae': 2,
          'Deltaproteobacteria': 6,
          'Blastocatellia (Subgroup 4)': 2}),
 'EveB18_4': Counter({'Alveolata': 399,
          'Gammaproteobacteria': 652,
          'Holozoa': 120,
          'Bacteroidia': 155,
          'unclassified_SAR': 13,
          'Alphaproteobacteria': 136,
          'Nucletmycea': 3,
          'Stramenopiles': 17,
          'Rhizaria': 6,
          'Deltaproteobacteria': 57,
          'Blastocatellia (Subgroup 4)': 7,
          'unclassified_Bacteroidetes': 3,
          'Planctomycetacia': 4,
          'Armatimonadia': 5,
          'Deinococci': 3,
          'Bacilli': 4,
          'Acidobacteriia': 3,
          'unclassified_Proteobacteria': 9,
          'Actinobacteria': 5,
          'Discoba': 6,
          'Sericytochromatia': 3,
          'Verrucomicrobiae': 1,
          'unclassified_Firmicutes': 1,
          'Chloroplastida': 1,
          'Oxyphotobacteria': 1}),
 'EveT18_1': Counter({'Holozoa': 273,
          'Alveolata': 67,
          'Gammaproteobacteria': 293,
          'Rhizaria': 7,
          'Bacteroidia': 82,
          'unclassified_SAR': 2,
          'Tubulinea': 2,
          'Armatimonadia': 12,
          'Alphaproteobacteria': 74,
          'Stramenopiles': 14,
          'Deltaproteobacteria': 31,
          'unclassified_Proteobacteria': 11,
          'Blastocatellia (Subgroup 4)': 4,
          'Actinobacteria': 7,
          'Oxyphotobacteria': 3,
          'Chloroplastida': 2,
          'Verrucomicrobiae': 7,
          'Acidobacteriia': 4,
          'Discosea': 3,
          'Deinococci': 2,
          'Nucletmycea': 2,
          'Anaerolineae': 1,
          'Chlamydiae': 1,
          'Nitrospira': 1,
          'Discoba': 1,
          'unclassified_Actinobacteria': 1,
          'Clostridia': 1,
          'Bacilli': 2,
          'Sericytochromatia': 1}),
 'EveB24_3': Counter({'Holozoa': 284,
          'Gammaproteobacteria': 552,
          'Alveolata': 60,
          'Alphaproteobacteria': 222,
          'Bacteroidia': 158,
          'Verrucomicrobiae': 14,
          'Armatimonadia': 4,
          'Bacilli': 14,
          'Actinobacteria': 4,
          'Deltaproteobacteria': 8,
          'Oxyphotobacteria': 2,
          'Leptospirae': 2,
          'Stramenopiles': 2,
          'unclassified_Proteobacteria': 2,
          'Deinococci': 2,
          'Sericytochromatia': 2,
          'Blastocatellia (Subgroup 4)': 2,
          'unclassified_Actinobacteria': 2}),
 'EvePB24_3': Counter({'Alveolata': 343,
          'Holozoa': 494,
          'Gammaproteobacteria': 443,
          'Bacteroidia': 124,
          'Alphaproteobacteria': 129,
          'unclassified_SAR': 4,
          'unclassified_Bacteroidetes': 9,
          'Stramenopiles': 4,
          'Deinococci': 7,
          'Armatimonadia': 4,
          'Oxyphotobacteria': 2,
          'Deltaproteobacteria': 7,
          'Verrucomicrobiae': 5,
          'Blastocatellia (Subgroup 4)': 3,
          'Sericytochromatia': 2,
          'Leptospirae': 1,
          'Actinobacteria': 2,
          'unclassified_Proteobacteria': 4,
          'Rhizaria': 1,
          'Planctomycetacia': 1,
          'Bacilli': 1}),
 'EveCd3_4': Counter({'Alveolata': 294,
          'Holozoa': 196,
          'Gammaproteobacteria': 410,
          'unclassified_Bacteroidetes': 26,
          'unclassified_SAR': 8,
          'Alphaproteobacteria': 113,
          'Bacteroidia': 82,
          'Blastocatellia (Subgroup 4)': 3,
          'Armatimonadia': 3,
          'Verrucomicrobiae': 4,
          'Actinobacteria': 1,
          'Stramenopiles': 2,
          'Bacilli': 3,
          'Rhizaria': 1,
          'Sericytochromatia': 1,

In [23]:
# make dataframe

df = pd.DataFrame.from_dict(samples, orient='index')
df

,Gammaproteobacteria,Alphaproteobacteria,Holozoa,Bacteroidia,Alveolata,Bacilli,Armatimonadia,unclassified_Proteobacteria,Actinobacteria,Verrucomicrobiae,...,Firmicutes,OM190,Erysipelotrichia,Spirochaetia,Subgroup 17,Nitrososphaeria,unclassified_Opisthokonta,Parcubacteria,Babeliae,unclassified_Patescibacteria
EveB3_2,670.0,284.0,52.0,152.0,42.0,16.0,6.0,22.0,6.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EveB12_4,149.0,22.0,38.0,24.0,111.0,8.0,NaN,1.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EveB6_1,206.0,68.0,83.0,49.0,63.0,NaN,2.0,5.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EveCd3_3,624.0,276.0,410.0,158.0,26.0,2.0,10.0,2.0,2.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EveB24_4,333.0,47.0,53.0,40.0,51.0,615.0,3.0,10.0,21.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
EveB18_1,526.0,138.0,67.0,144.0,228.0,1.0,6.0,22.0,4.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Eve10LT3_4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,...,804.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Eve10LT3_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EveB3_3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Eve10LT24_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# replace NaNs by 0

df.fillna(0, inplace=True)
df = df.astype('float')
df

,Gammaproteobacteria,Alphaproteobacteria,Holozoa,Bacteroidia,Alveolata,Bacilli,Armatimonadia,unclassified_Proteobacteria,Actinobacteria,Verrucomicrobiae,...,Firmicutes,OM190,Erysipelotrichia,Spirochaetia,Subgroup 17,Nitrososphaeria,unclassified_Opisthokonta,Parcubacteria,Babeliae,unclassified_Patescibacteria
EveB3_2,670.0,284.0,52.0,152.0,42.0,16.0,6.0,22.0,6.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EveB12_4,149.0,22.0,38.0,24.0,111.0,8.0,0.0,1.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EveB6_1,206.0,68.0,83.0,49.0,63.0,0.0,2.0,5.0,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EveCd3_3,624.0,276.0,410.0,158.0,26.0,2.0,10.0,2.0,2.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EveB24_4,333.0,47.0,53.0,40.0,51.0,615.0,3.0,10.0,21.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
EveB18_1,526.0,138.0,67.0,144.0,228.0,1.0,6.0,22.0,4.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Eve10LT3_4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,...,804.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Eve10LT3_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EveB3_3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Eve10LT24_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0